name: PBRP Build - M14x (Dependency Fix)

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/PitchBlackRecoveryProject/manifest_pb.git
  MANIFEST_BRANCH: android-12.1
  DEVICE_NAME: m14x
  DEVICE_PATH: device/samsung/m14x
  COMMON_PATH: device/samsung/s5e8535-common
  LUNCH_NAME: pb_m14x-eng

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 10240 # Increased swap for compilation stability
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install Legacy Dependencies
        run: |
          sudo apt update
          # Install current available packages
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib \
          gcc-multilib git gnupg gperf imagemagick lib32readline-dev \
          lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev \
          libxml2 libxml2-utils lzop pngcrush rsync testers schedtool squashfs-tools tar zip \
          zlib1g-dev python3
          
          # Manually install Python2 and Libncurses5 (The "Focal" fix)
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python-defaults/python2_2.7.17-2ubuntu4_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7_2.7.18-1~20.04.4_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-minimal_2.7.18-1~20.04.4_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-minimal_2.7.18-1~20.04.4_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-stdlib_2.7.18-1~20.04.4_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.2-0ubuntu2_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb
          
          sudo dpkg -i *.deb || sudo apt -f install -y

      - name: Setup Repo & Git
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Sync PBRP Source
        run: |
          mkdir work && cd work
          repo init -u ${{ env.MANIFEST }} -b ${{ env.MANIFEST_BRANCH }} --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Clone Device Trees
        run: |
          cd work
          git clone https://github.com/AshutoshCodeSpace/twrp_device_samsung_m14x ${{ env.DEVICE_PATH }}
          git clone https://github.com/s5e8535/twrp_device_samsung_s5e8535-common ${{ env.COMMON_PATH }}

      - name: Patch Tree for PitchBlack
        run: |
          cd work/${{ env.DEVICE_PATH }}
          # Logic to handle both twrp_ and omni_ prefixes
          if [ -f twrp_m14x.mk ]; then
            mv twrp_m14x.mk pb_m14x.mk
          elif [ -f omni_m14x.mk ]; then
            mv omni_m14x.mk pb_m14x.mk
          fi
          
          sed -i 's/twrp_m14x/pb_m14x/g' AndroidProducts.mk
          sed -i 's/omni_m14x/pb_m14x/g' AndroidProducts.mk
          sed -i 's/twrp_/pb_/g' pb_m14x.mk || sed -i 's/omni_/pb_/g' pb_m14x.mk
          
          # Samsung specific build flags
          echo "PB_RECOVERY_DEVICE := m14x" >> BoardConfig.mk
          echo "PB_MAINTAINER := GitHubAction" >> BoardConfig.mk

      - name: Build PBRP
        run: |
          cd work
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C
          source build/envsetup.sh
          lunch ${{ env.LUNCH_NAME }}
          mka pbrp -j$(nproc --all)

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: PBRP-M14x-Final
          path: |
            work/out/target/product/m14x/PitchBlack-*.zip
            work/out/target/product/m14x/recovery.img
            
