name: Build PBRP m14x
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cleanup Space
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /var/lib/mysql
          sudo apt-get clean

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential git-core libssl-dev python3 repo libncurses5 zip unzip curl git lz4

      - name: Sync PBRP Source
        run: |
          mkdir pbrp && cd pbrp
          git config --global user.email "builder@example.com"
          git config --global user.name "Builder"
          
          # Initialize PBRP Minimal Manifest (Android 12.1)
          repo init -u https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-12.1 --depth=1
          
          # Inject Local Manifest
          mkdir -p .repo/local_manifests
          cat <<EOF > .repo/local_manifests/m14x.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <project name="kawaldhanju33062-tech/twrp_device_samsung_m14x" path="device/samsung/m14x" remote="github" revision="main" />
            <project name="kawaldhanju33062-tech/twrp_device_samsung_s5e8535-common" path="device/samsung/s5e8535-common" remote="github" revision="main" />
          </manifest>
          EOF
          
          # Sync all trees
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Build PBRP
        run: |
          cd pbrp
          export ALLOW_MISSING_DEPENDENCIES=true
          . build/envsetup.sh
          
          # Use the product name defined in your pb_m14x.mk
          lunch pb_m14x-eng
          
          # Compile the PBRP image
          mka pbrp -j$(nproc --all)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PBRP-m14x-Build
          path: |
             pbrp/out/target/product/m14x/PBRP*.zip
             pbrp/out/target/product/m14x/recovery.img
             
